# Generated by Django 4.1.7 on 2023-05-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApi', '0002_alter_quizquestions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
